name: Build and Release Poetry Package

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true
        
    - name: Configure Poetry
      run: poetry config virtualenvs.in-project true
      
    - name: Install dependencies
      run: poetry install
      
    #- name: Run tests (optional)
    #  run: |
    #    if poetry run python -c "import pytest" 2>/dev/null; then
    #      poetry run pytest
    #    else
    #      echo "No pytest found, skipping tests"
    #    fi
    #  continue-on-error: false
      
    - name: Build package (wheel only)
      run: poetry build --format wheel
      
    - name: Get tag name
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: ${{ steps.tag.outputs.tag }}
        files: |
          dist/*.whl
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    #- name: Publish to PyPI (optional)
    #  if: startsWith(github.ref, 'refs/tags/')
    #  run: |
    #    poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
    #    poetry publish
    #  continue-on-error: true
